# Generated by Django 3.2.7 on 2021-10-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20210705_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.FileField(upload_to='service_images/'),
        ),
    ]
